### ISSUE TITLE
return random point given cell ID

### ISSUE THREAD

**Issue by trhi** [Dozed12/p5.voronoi#2]
Suggestion for a function. 

Returns a random point within the cell given the cell ID. 

Doable?

**Comment by Dozed12** [comment]
An interesting suggestion but perhaps outside the scope of the library since this can be summarized as getting a random point inside a convex polygon, which isn't voronoi specific.

This is usually done by:

- Triangulating the cell(convex polygon) (https://en.wikipedia.org/wiki/Polygon_triangulation)
- Picking random triangle
- Picking random point inside the triangle (https://stackoverflow.com/questions/47410054/generate-random-locations-within-a-triangular-domain)
